# Generated by Django 3.2.7 on 2021-10-12 08:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Cropper', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Photo',
        ),
    ]
